### ISSUE TITLE
XenForms Download

### ISSUE THREAD

**Issue by superbrains** [michaeled/XenForms#5]
Hi,

I have been trying to download XenForms for the past 2 days @www.xenforms.com Without any Luck. Where can I download XenForms? I'm so impressed with the testimonies and would want to be a part of it. Great Job!!!!!

**Comment by michaeled** [comment]
Hey there,

There's a "Download Beta" button near the top of the site. i just clicked it and the setup started downloading. Let me know if it's been down. 

[XenForms web site](https://www.xenforms.com)

**Comment by superbrains** [comment]
The Site (www.xenforms.com) is DOWN Sir.

**Comment by michaeled** [comment]
My site monitoring hasn't reported any downtime today. It checks the site every 3 minutes from 6 countries... I'm curious why you can't bring up the site. Do you get any specific error?

Anyways, here's the [direct CDN](http://adcb143ec793670fcdce-ce866c67c537bf74cea220688781c5c2.r94.cf1.rackcdn.com/Beta5/Setup.exe) link to the latest binaries.

**Comment by superbrains** [comment]
Thanks Michaeled, The Link you sent worked.

**Comment by superbrains** [comment]
Meanwhile, the site wont come up. It just shows up Blank. I'm accessing it from Nigeria. Once again, thanks for the Link.

**Comment by superbrains** [comment]
One More Question. Though I won't know if there's a documentation since I cannot access the site. Do you have Any Quick Start Documentation?

**Comment by michaeled** [comment]
I do, but it's on the web site. I'll eventually place it here in wiki.
